### ISSUE TITLE
copilot init unknown flag: --svc

### ISSUE THREAD

**Issue by yysu** [aws-samples/aws-copilot-sample-service#5]
The Deploying command on the RREAD.me file can not work. 
```
copilot init --app demo                  \
  --svc api                              \
  --svc-type 'Load Balanced Web Service' \
  --dockerfile './Dockerfile'            \ 
  --deploy

unknown flag: --svc
```

Checking the [copilot-cli Release](https://github.com/aws/copilot-cli/releases), I notice there are some breaking changes like:
- Breaking change: The --svc flag is renamed to --name and --svc-type to --type for the copilot init command to accommodate for new workload types.

Therefore, I have opened a [PR](https://github.com/aws-samples/aws-copilot-sample-service/pull/4) to fix the command.

**Comment by kohidave** [comment]
Thank you! We merged in this fix <3
