### ISSUE TITLE
Deploy your first application returns 404

### ISSUE THREAD

**Issue by suroh1994** [aws-samples/aws-copilot-sample-service#7]
Hello, 
I've been following the steps in the [documentation](https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/) for deploying my first application and it successfully deployed on AWS. I then clicked the URL shown in the console and got to a 404 page. After looking at the logs (copilot svc logs)
```
copilot/example-app/408f9 2022/08/26 09:34:39 [error] 31#31: *116 "/usr/share/nginx/html/example-app/index.html" is not found (2: No such file or directory), client: 10.0.1.199, server: localhost, request: "GET /example-app/ HTTP/1.1", host: "examp-publi-18dec46ypctqj-243473654.eu-west-1.elb.amazonaws.com"
```
and the Dockerfile in this repo,
```
COPY index.html /usr/share/nginx/html
```
 
 I noticed that the index.html file is being copied to the root of the nginx html directory. This works fine when I run the image locally, but once it's in ECS, the URL has the application name append, which leads to nginx looking for a file under `/usr/share/nginx/html/<application name>/index.html`, which does not exist.

I believe this is an error in the documentation or repository and should be fixed, as it was very confusing to me.

**Comment by paragbhingre** [comment]
@suroh1994 we have fixed the issue and I have tested it locally too. Could you please clone the repo again and try deploying the sample application? Feel free to reopen the issue if it doesn't work.

**Comment by suroh1994** [comment]
Hi @paragbhingre thanks for the quick fix, that did indeed solve the issue. The deployment now works as described in the wiki!
